#!/bin/bash
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar height=37        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=10  \
                 padding_right=10 \
                 color=$BAR_COLOR

##### Changing Defaults #####
sketchybar --default icon.font="SF Pro:Semibold:15.0"  \
                     icon.color=$BAR_COLOR             \
                     label.font="SF Pro:Semibold:15.0" \
                     label.color=$BAR_COLOR            \
                     padding_left=5                    \
                     padding_right=5                   \
                     label.padding_left=10             \
                     label.padding_right=10            \
                     icon.padding_left=4               \
                     icon.padding_right=4              \
                     background.color=$ITEM_BG_COLOR   \
                     background.corner_radius=5        \
                     background.height=24              \

##### Adding aerospace layouts #####
sketchybar --add event aerospace_workspace_change

# Add workspaces for all valid monitors
for monitor in $(aerospace list-monitors --format "%{monitor-appkit-nsscreen-screens-id}"); do
  if [[ "$monitor" =~ ^[1-2]$ ]]; then  # Ensure only valid monitor IDs are processed
    for sid in $(aerospace list-workspaces --monitor "$monitor"); do
      display_id="$monitor"
      
      sketchybar --add item space.$sid left \
        --set space.$sid display="$display_id" \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        drawing=on \
        background.color=$BAR_COLOR \
        background.corner_radius=5 \
        background.drawing=on \
        background.border_color=0xAAFFFFFF \
        background.border_width=0 \
        background.height=25 \
        icon="$sid" \
        icon.color=$ACCENT_COLOR \
        icon.padding_left=10 \
        label.font="sketchybar-app-font:Regular:16.0" \
        label.color=$ACCENT_COLOR \
        label.padding_right=10 \
        label.padding_left=0 \
        label.y_offset=0 \
        label.shadow.drawing=off \
        click_script="aerospace workspace $sid" \
        script="$PLUGIN_DIR/space.sh"
    done
  else
    echo "Invalid monitor ID: $monitor"
  fi
done

# Load Icons on startup for all monitors
#for monitor in $(aerospace list-monitors); do
#  if [[ "$monitor" =~ ^[1-2]$ ]]; then  # Only process valid IDs
#    for sid in $(aerospace list-workspaces --monitor "$monitor" --empty no); do
#      apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')
#
#      sketchybar --set space.$sid drawing=on \
#        label.y_offset=-1
#
#      icon_strip=" "
#      if [ "${apps}" != "" ]; then
#        while read -r app; do
#          icon_strip+=" $($CONFIG_DIR/plugins/icon_map_fn.sh "$app")"
#        done <<<"${apps}"
#      else
#        icon_strip=""
#      fi
#      sketchybar --set space.$sid label="$icon_strip"
#    done
#  fi
#done

##### Adding Left Items #####
# We add some regular items to the left side of the bar
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh
source $ITEM_DIR/media.sh

##### Adding Right Items #####
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh

##### Finalizing Setup #####
sketchybar --update
